[package]
name = "wumpus_hunt"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { version = "0.4.38", features = ["serde"] }
dioxus = "0.5.1"
rand = "0.8.5"
getrandom = { version = "0.2", features = ["js"] }
